name: .NET Pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Application
      run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & Push API Docker image
      with:
        image: croziernn/cloudfoundryapp
        tags: version1.0.0, latest
        dockerfile: ./CloudFoundryApp.API/Dockerfile
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
